name: Run parser
on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * 5"
  push:
jobs:
  RunParser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run parser
        shell: pwsh
        run: |
          try {
            $env:PYTHONIOENCODING="utf-8"
            python3 -m venv venv
            & ./venv/bin/Activate.ps1
            pip install -r requirements.txt
            python3 main.py
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update data"
            git push
          }
          catch {
            write-host "No changes made"
          }
